const pages = [
    
{id:1,name:"Agonil Cream",url:"Agonil.html"},
{id:	2	,	name:	"Alleloc",	url:	"Alleloc.html"	},
{id:	3	,	name:	"Allertin",	url:	"Allertin.html"	},
{id:	4	,	name:	"Aloglip",	url:	"Aloglip.html"	},
{id:	5	,	name:	"Arokast",	url:	"Arokast.html"	},
{id:	6	,	name:	"Artiforte",	url:	"Artiforte.html"	},
{id:	7	,	name:	"Artifresh Liquigel",	url:	"Artifresh Liquigel.html"	},
{id:	8	,	name:	"Azirox",	url:	"Azirox.html"	},
{id:	9	,	name:	"Bonacerin",	url:	"Bonacerin.html"	},
{id:	10	,	name:	"Bondro",	url:	"Bondro.html"	},
{id:	11	,	name:	"Brox",	url:	"Brox.html"	},
{id:	12	,	name:	 "Cfresh.html"	url:	 "Cfresh",	},
{id:	13	,	name:	            "Clascon.html"	url:	       "Clascon",	},
{id:	14	,	name:	            "Clincin.html"	url:	            "Clincin",	},
{id:	15	,	name:	            "Clonipres.html"	url:	            "Clonipres",	},
{id:	16	,	name:	            "Conpan.html"	url:	            "Conpan",	},
{id:	17	,	name:	            "Curafin.html"	url:	            "Curafin",	},
{id:	18	,	name:	            "Dextac.html"	url:	            "Dextac",	},
{id:	19	,	name:	            "Diplin.html"	url:	            "Diplin",	},
{id:	20	,	name:	            "Duracef.html"	url:	            "Duracef",	},
{id:	21	,	name:	            "Ertuglif.html"	url:	            "Ertuglif",	},
{id:	22	,	name:	            "Esona.html"	url:	            "Esona",	},
{id:	23	,	name:	            "Esotac.html"	url:	            "Esotac",	},
{id:	24	,	name:	            "Ezitor.html"	url:	            "Ezitor",	},
{id:	25	,	name:	            "Faropen.html"	url:	            "Faropen",	},
{id:	26	,	name:	            "Feelfree Contraceptive Gel.html"	url:	            "Feelfree Contraceptive Gel",	},
{id:	27	,	name:	            "Filodox.html"	url:	            "Filodox",	},
{id:	28	,	name:	            "Fixcef.html"	url:	            "Fixcef",	},
{id:	29	,	name:	            "Flutispray.html"	url:	            "Flutispray",	},
{id:	30	,	name:	            "Frucard.html"	url:	            "Frucard",	},
{id:	31	,	name:	            "Gefomag.html"	url:	            "Gefomag",	},
{id:	32	,	name:	            "Glifomet.html"	url:	            "Glifomet",	},
{id:	33	,	name:	            "Glix.html"	url:	            "Glix",	},
{id:	34	,	name:	            "Itopri.html"	url:	            "Itopri",	},
{id:	35	,	name:	            "Itracon.html"	url:	            "Itracon",	},
{id:	36	,	name:	            "Joytrip.html"	url:	            "Joytrip",	},
{id:	37	,	name:	            "Kcit.html"	url:	            "Kcit",	},
{id:	38	,	name:	            "Kindical.html"	url:	            "Kindical",	},
{id:	39	,	name:	            "L Amlo.html"	url:	            "L Amlo",	},
{id:	40	,	name:	            "Lipostat.html"	url:	            "Lipostat",	},
{id:	41	,	name:	            "Lopesim.html"	url:	            "Lopesim",	},
{id:	42	,	name:	            "Loxodol.html"	url:	            "Loxodol",	},
{id:	43	,	name:	            "Lulider.html"	url:	            "Lulider",	},
{id:	44	,	name:	            "Lumilast.html"	url:	            "Lumilast",	},
{id:	45	,	name:	            "Malifa.html"	url:	            "Malifa",	},
{id:	46	,	name:	            "Megamag.html"	url:	            "Megamag",	},
{id:	47	,	name:	            "Meltix.html"	url:	            "Meltix",	},
{id:	48	,	name:	            "Methebac.html"	url:	            "Methebac",	},
{id:	49	,	name:	            "Nafgal Cream.html"	url:	            "Nafgal Cream",	},
{id:	50	,	name:	            "Navacef.html"	url:	            "Navacef",	},
{id:	51	,	name:	            "Navix Navix Plus.html"	url:	            "Navix Navix Plus",	},
{id:	52	,	name:	            "Neumir.html"	url:	            "Neumir",	},
{id:	53	,	name:	            "N-bion.html"	url:	            "N-bion",	},
{id:	54	,	name:	            "Nabuton.html"	url:	            "Nabuton",	},
{id:	55	,	name:	            "Olmepin.html"	url:	            "Olmepin",	},
{id:	56	,	name:	            "Omaglip.html"	url:	            "Omaglip",	},
{id:	57	,	name:	            "Osmina.html"	url:	            "Osmina",	},
{id:	58	,	name:	            "Otecon.html"	url:	            "Otecon",	},
{id:	59	,	name:	            "Phoscon.html"	url:	            "Phoscon",	},
{id:	60	,	name:	            "Pires D M.html"	url:	            "Pires D M",	},
{id:	61	,	name:	            "Pizofen Imigra.html"	url:	            "Pizofen Imigra",	},
{id:	62	,	name:	            "Pmec Cream.html"	url:	            "Pmec Cream",	},
{id:	63	,	name:	            "Pravalip.html"	url:	            "Pravalip",	},
{id:	64	,	name:	            "Pregan.html"	url:	            "Pregan",	},
{id:	65	,	name:	            "Prulicon.html"	url:	            "Prulicon",	},
{id:	66	,	name:	            "Rabetac.html"	url:	            "Rabetac",	},
{id:	67	,	name:	            "Sicmon.html"	url:	            "Sicmon",	},
{id:	68	,	name:	            "Somalax.html"	url:	            "Somalax",	},
{id:	69	,	name:	            "Steclo.html"	url:	            "Steclo",	},
{id:	70	,	name:	            "Sudoderm.html"	url:	            "Sudoderm",	},
{id:	71	,	name:	            "Sulderm.html	url:	            "Sulderm.html	},
{id:	72	,	name:	            "Tabis.html"	url:	            "Tabis",	},
{id:	73	,	name:	            "Tencef.html"	url:	            "Tencef",	},
{id:	74	,	name:	            "Torcox.html"	url:	            "Torcox",	},
{id:	75	,	name:	            "Urinide.html"	url:	            "Urinide",	},
{id:	76	,	name:	            "Vanogut.html"	url:	            "Vanogut",	},
{id:	77	,	name:	            "Vaspec MR.html"	url:	            "Vaspec MR",	},
{id:	78	,	name:	            "Vontac.html"	url:	            "Vontac",	},
{id:	79	,	name:	            "Zenocin.html"	url:	            "Zenocin",	},
{id:	80	,	name:	            "Price List.html"	url:	            "Price List",	},
{id:	81	,	name:	            "FAQ.html"	url:	            "FAQ",	},
{id:	82	,	name:	            "Blank.html"	url:	            "Blank",	},
{id:	82	,	name:	"Blank",	url:	"Blank.html"	},
    
];

