const pages = [
    
{id:	1	,	name:	"Agonil Cream",	url:	"Agonil.html"	},
{id:	2	,	name:	"Alleloc",	url:	"Alleloc.html"	},
{id:	3	,	name:	"Allertin",	url:	"Allertin.html"	},
{id:	4	,	name:	"Aloglip",	url:	"Aloglip.html"	},
{id:	5	,	name:	"Arokast",	url:	"Arokast.html"	},
{id:	6	,	name:	"Artiforte",	url:	"Artiforte.html"	},
{id:	7	,	name:	"Artifresh Liquigel",	url:	"Artifresh Liquigel.html"	},
{id:	8	,	name:	"Azirox",	url:	"Azirox.html"	},
{id:	9	,	name:	"Bonacerin",	url:	"Bonacerin.html"	},
{id:	10	,	name:	"Bondro",	url:	"Bondro.html"	},
{id:	11	,	name:	"Brox",	url:	"Brox.html"	},
{id:	12	,	name:	"Cfresh",	url:	"Cfresh.html"	},
{id:	13	,	name:	"Clascon",	url:	"Clascon.html"	},
{id:	14	,	name:	"Clincin",	url:	"Clincin.html"	},
{id:	15	,	name:	"Clonipres",	url:	"Clonipres.html"	},
{id:	16	,	name:	"Conpan",	url:	"Conpan.html"	},
{id:	17	,	name:	"Curafin",	url:	"Curafin.html"	},
{id:	18	,	name:	"Dextac",	url:	"Dextac.html"	},
{id:	19	,	name:	"Diplin",	url:	"Diplin.html"	},
{id:	20	,	name:	"Duracef",	url:	"Duracef.html"	},
{id:	21	,	name:	"Ertuglif",	url:	"Ertuglif.html"	},
{id:	22	,	name:	"Esona",	url:	"Esona.html"	},
{id:	23	,	name:	"Esotac",	url:	"Esotac.html"	},
{id:	24	,	name:	"Ezitor",	url:	"Ezitor.html"	},
{id:	25	,	name:	"Faropen",	url:	"Faropen.html"	},
{id:	26	,	name:	"Feelfree Contraceptive Gel",	url:	"Feelfree Contraceptive Gel.html"	},
{id:	27	,	name:	"Filodox",	url:	"Filodox.html"	},
{id:	28	,	name:	"Fixcef",	url:	"Fixcef.html"	},
{id:	29	,	name:	"Flutispray",	url:	"Flutispray.html"	},
{id:	30	,	name:	"Freescab",	url:	"Freescab.html"	},
{id:	31	,	name:	"Frucard",	url:	"Frucard.html"	},
{id:	32	,	name:	"Glifomet",	url:	"Glifomet.html"	},
{id:	33	,	name:	"Glix",	url:	"Glix.html"	},
{id:	34	,	name:	"Itopri",	url:	"Itopri.html"	},
{id:	35	,	name:	"Itracon",	url:	"Itracon.html"	},
{id:	36	,	name:	"Joytrip",	url:	"Joytrip.html"	},
{id:	37	,	name:	"Kcit",	url:	"Kcit.html"	},
{id:	38	,	name:	"Kindical",	url:	"Kindical.html"	},
{id:	39	,	name:	"L Amlo",	url:	"L Amlo.html"	},
{id:	40	,	name:	"Lipostat",	url:	"Lipostat.html"	},
{id:	41	,	name:	"Lopesim",	url:	"Lopesim.html"	},
{id:	42	,	name:	"Loxodol",	url:	"Loxodol.html"	},
{id:	43	,	name:	"Lulider",	url:	"Lulider.html"	},
{id:	44	,	name:	"Lumilast",	url:	"Lumilast.html"	},
{id:	45	,	name:	"Malifa",	url:	"Malifa.html"	},
{id:	46	,	name:	"Megamag",	url:	"Megamag.html"	},
{id:	47	,	name:	"Meltix",	url:	"Meltix.html"	},
{id:	48	,	name:	"Methebac",	url:	"Methebac.html"	},
{id:	49	,	name:	"Nafgal Cream",	url:	"Nafgal Cream.html"	},
{id:	50	,	name:	"Navacef",	url:	"Navacef.html"	},
{id:	51	,	name:	"Navix Navix Plus",	url:	"Navix Navix Plus.html"	},
{id:	52	,	name:	"Neumir",	url:	"Neumir.html"	},
{id:	53	,	name:	"N-bion",	url:	"N-bion.html"	},
{id:	54	,	name:	"Nabuton",	url:	"Nabuton.html"	},
{id:	55	,	name:	"Olmepin",	url:	"Olmepin.html"	},
{id:	56	,	name:	"Omaglip",	url:	"Omaglip.html"	},
{id:	57	,	name:	"Osmina",	url:	"Osmina.html"	},
{id:	58	,	name:	"Otecon",	url:	"Otecon.html"	},
{id:	59	,	name:	"Phoscon",	url:	"Phoscon.html"	},
{id:	60	,	name:	"PiresDM",	url:	"Pires D M.html"	},
{id:	61	,	name:	"Pizofen Imigra",	url:	"Pizofen Imigra.html"	},
{id:	62	,	name:	"PmecCream",	url:	"Pmec Cream.html"	},
{id:	63	,	name:	"Pravalip",	url:	"Pravalip.html"	},
{id:	64	,	name:	"Pregan",	url:	"Pregan.html"	},
{id:	65	,	name:	"Prulicon",	url:	"Prulicon.html"	},
{id:	66	,	name:	"Rabetac",	url:	"Rabetac.html"	},
{id:	67	,	name:	"Sicmon",	url:	"Sicmon.html"	},
{id:	68	,	name:	"Somalax",	url:	"Somalax.html"	},
{id:	69	,	name:	"Steclo",	url:	"Steclo.html"	},
{id:	70	,	name:	"Sudoderm",	url:	"Sudoderm.html"	},
{id:	71	,	name:	"Sulderm.html",	url:	"Sulderm.html"	},
{id:	72	,	name:	"Tabis",	url:	"Tabis.html"	},
{id:	73	,	name:	"Tencef",	url:	"Tencef.html"	},
{id:	74	,	name:	"Torcox",	url:	"Torcox.html"	},
{id:	75	,	name:	"Urinide",	url:	"Urinide.html"	},
{id:	76	,	name:	"Vanogut",	url:	"Vanogut.html"	},
{id:	77	,	name:	"Vaspec MR",	url:	"Vaspec MR.html"	},
{id:	78	,	name:	"Vontac",	url:	"Vontac.html"	},
{id:	79	,	name:	"Zenocin",	url:	"Zenocin.html"	},
{id:	80	,	name:	"Price List",	url:	"Price List.html"	},
{id:	81	,	name:	"FAQ",	url:	"FAQ.html"	},
{id:	82	,	name:	"Blank",	url:	"Blank.html"	},



];
